### ISSUE TITLE
Question builder results blank

### ISSUE THREAD

**Issue by ntuck** [RobokopU24/Issues#235] opened 2024-10-14 18:43 UTC
In rerunning a query, the results page is blank. Transient issue?

![image](https://github.com/user-attachments/assets/0f4b373f-acfa-44e2-ac4d-37284081b919)

![image](https://github.com/user-attachments/assets/7fc423cc-d033-4265-90fe-56c504d08df7)

**Comment by EvanDietzMorris** [comment] 2024-10-14 20:34
This is what is shown when an error is cached by Aragorn. I can't reproduce this one from the screenshot. The TRAPI query itself is always more helpful for troubleshooting.

**Comment by ntuck** [comment] 2024-10-15 12:47
Does this help? 

{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "ids": [
            "NCBIGene:196"
          ],
          "categories": [
            "biolink:Gene",
            "biolink:GeneOrGeneProduct",
            "biolink:GenomicEntity",
            "biolink:ChemicalEntityOrGeneOrGeneProduct",
            "biolink:PhysicalEssence",
            "biolink:OntologyClass",
            "biolink:BiologicalEntity",
            "biolink:ThingWithTaxon",
            "biolink:NamedThing",
            "biolink:Entity",
            "biolink:PhysicalEssenceOrOccurrent",
            "biolink:MacromolecularMachineMixin"
          ],
          "name": "AHR"
        },
        "n1": {
          "categories": [
            "biolink:Gene"
          ],
          "name": "Gene"
        },
        "n2": {
          "ids": [
            "MONDO:0004790"
          ],
          "categories": [
            "biolink:Disease",
            "biolink:DiseaseOrPhenotypicFeature",
            "biolink:BiologicalEntity",
            "biolink:ThingWithTaxon",
            "biolink:NamedThing",
            "biolink:Entity"
          ],
          "name": "fatty liver disease"
        }
      },
      "edges": {
        "e0": {
          "subject": "n0",
          "object": "n1",
          "predicates": [
            "biolink:related_to"
          ],
          "qualifier_constraints": [
            {
              "qualifier_set": []
            }
          ]
        },
        "e1": {
          "subject": "n1",
          "object": "n2",
          "predicates": [
            "biolink:related_to"
          ],
          "qualifier_constraints": [
            {
              "qualifier_set": []
            }
          ]
        }
      }
    },
    "results": []
  }
}

**Comment by EvanDietzMorris** [comment] 2024-10-15 15:12
Yup. It was an error cached in Aragorn. Unfortunately, it's practically impossible to tell what caused it with the error message saved by Aragorn. I personally think we should consider retrying the query in cases like that but the Aragorn folks didn't agree on that previously. I cleared the cache and the query worked, so it should give back the right results now.

**Comment by EvanDietzMorris** [comment] 2024-10-15 15:13
I'm going to close this one, but I'll make a comment on the error displaying issue about this if we want to continue the discussion there.

**Closed as completed by EvanDietzMorris** 2024-10-15 15:13 UTC
Labels: bug, AIM 3
